//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstAidForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePertolongan
    {
        public int Id { get; set; }
        public string Kasus { get; set; }
        public string Penanganan { get; set; }
        public string Gejala { get; set; }
    }
}
